title: Chaeyoon Kim
url: https://chaeyoonyunakim.github.io
description: Data Scientist at NHS England. Writing about data science, AI, and health.

permalink: /:year/:month/:day/:title/

plugins: [jekyll-feed]

collections:
  projects:
    output: false
    sort_by: order

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'vendor']
